### ISSUE TITLE
カテゴリ一覧表示

### ISSUE THREAD

**Issue by tsu-nera** [futurismo-org/titan#73]
参加可能なカテゴリをならべる。

### /categories のページをつくる

参考
https://github.com/futurismo-org/titan/blob/master/reactjs/src/components/organisms/Challenges.jsx

### Firebase Firestoreにデータを手動で作成する

Web UIから。NoSQLに慣れる。やりかたはいろいろいじっているとできるかも。

### FIrebase Cloud Functionからデータを取り出すコードを書く

challengesを参考にデータを取り出す。
https://github.com/futurismo-org/titan/blob/master/firebase/functions/graphql/data/resolvers.js#L12

challengesを参考にスキーマを定義
https://github.com/futurismo-org/titan/blob/master/firebase/functions/graphql/data/schema.js

ここにアクセスすると、GraphQL Playgroundがたちあがるので、ここからGraphQLを発行してみる。
http://localhost:5000/titan-dev-1234/asia-northeast1/api
https://asia-northeast1-titan-dev-1234.cloudfunctions.net/api

### Reactからデータを取得して一覧表示

参考にしてつくる。
https://github.com/futurismo-org/titan/blob/master/reactjs/src/components/organisms/Challenges.jsx

注意点は、React Hooksの形式で書く。Class Componentはレガシーなのでつかわない。

**Comment by tsu-nera** [comment]
[![Screenshot from Gyazo](https://gyazo.com/baf569df29174e7a09219704a3322310/raw)](https://gyazo.com/baf569df29174e7a09219704a3322310)

こんな感じで。

## カテゴリ一覧

- 筋トレ
- 瞑想

**Comment by tsu-nera** [comment]
@all-contributors please add @tsu-nera for code

**Comment by tsu-nera** [comment]
@all-contributors please add @Goi666  for code

**Comment by tsu-nera** [comment]
チャレンジ一覧にはデザインを当てましたが、とりあえずこのissueではカテゴリ一覧は素のリストでよいです。デザインはあとで当てます。

**Comment by Goi666** [comment]
一旦クローズ。デザインはあとで当てる。現在はチャレンジページと全く同じ構成。
